/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public class AgentFailReasonVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AgentFailReasonVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AgentFailReasonVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UtpCoreAccessLibJNI.delete_AgentFailReasonVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AgentFailReasonVector() {
    this(UtpCoreAccessLibJNI.new_AgentFailReasonVector__SWIG_0(), true);
  }

  public AgentFailReasonVector(long n) {
    this(UtpCoreAccessLibJNI.new_AgentFailReasonVector__SWIG_1(n), true);
  }

  public long size() {
    return UtpCoreAccessLibJNI.AgentFailReasonVector_size(swigCPtr, this);
  }

  public long capacity() {
    return UtpCoreAccessLibJNI.AgentFailReasonVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    UtpCoreAccessLibJNI.AgentFailReasonVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return UtpCoreAccessLibJNI.AgentFailReasonVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    UtpCoreAccessLibJNI.AgentFailReasonVector_clear(swigCPtr, this);
  }

  public void add(AgentFailReason x) {
    UtpCoreAccessLibJNI.AgentFailReasonVector_add(swigCPtr, this, AgentFailReason.getCPtr(x), x);
  }

  public AgentFailReason get(int i) {
    long cPtr = UtpCoreAccessLibJNI.AgentFailReasonVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new AgentFailReason(cPtr, false);
  }

  public void set(int i, AgentFailReason val) {
    UtpCoreAccessLibJNI.AgentFailReasonVector_set(swigCPtr, this, i, AgentFailReason.getCPtr(val), val);
  }

}
