/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public class AgentLiveList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AgentLiveList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AgentLiveList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UtpCoreAccessLibJNI.delete_AgentLiveList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AgentLiveList() {
    this(UtpCoreAccessLibJNI.new_AgentLiveList(), true);
  }

  public String getTestObjectId() {
    return UtpCoreAccessLibJNI.AgentLiveList_getTestObjectId(swigCPtr, this);
  }

  public LiveAgentVector getLiveAgents() {
    long cPtr = UtpCoreAccessLibJNI.AgentLiveList_getLiveAgents(swigCPtr, this);
    return (cPtr == 0) ? null : new LiveAgentVector(cPtr, false);
  }

}
