/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public class AgentLiveListVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AgentLiveListVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AgentLiveListVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UtpCoreAccessLibJNI.delete_AgentLiveListVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AgentLiveListVector() {
    this(UtpCoreAccessLibJNI.new_AgentLiveListVector(), true);
  }

  public void add(AgentLiveList agent) {
    UtpCoreAccessLibJNI.AgentLiveListVector_add(swigCPtr, this, AgentLiveList.getCPtr(agent), agent);
  }

  public int size() {
    return UtpCoreAccessLibJNI.AgentLiveListVector_size(swigCPtr, this);
  }

  public AgentLiveList get(int i) {
    long cPtr = UtpCoreAccessLibJNI.AgentLiveListVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new AgentLiveList(cPtr, false);
  }

}
