/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public class AnalyzeInvokeResult extends BoolInvokeResult {
  private long swigCPtr;

  protected AnalyzeInvokeResult(long cPtr, boolean cMemoryOwn) {
    super(UtpCoreAccessLibJNI.AnalyzeInvokeResult_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AnalyzeInvokeResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UtpCoreAccessLibJNI.delete_AnalyzeInvokeResult(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AnalyzeInvokeResult() {
    this(UtpCoreAccessLibJNI.new_AnalyzeInvokeResult(), true);
  }

  public String getScriptId() {
    return UtpCoreAccessLibJNI.AnalyzeInvokeResult_getScriptId(swigCPtr, this);
  }

  public long getIndex() {
    return UtpCoreAccessLibJNI.AnalyzeInvokeResult_getIndex(swigCPtr, this);
  }

  public String getErrMsg() {
    return UtpCoreAccessLibJNI.AnalyzeInvokeResult_getErrMsg(swigCPtr, this);
  }

}
