/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public class BoolInvokeResult {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BoolInvokeResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BoolInvokeResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UtpCoreAccessLibJNI.delete_BoolInvokeResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BoolInvokeResult() {
    this(UtpCoreAccessLibJNI.new_BoolInvokeResult(), true);
  }

  public boolean getBoolResult() {
    return UtpCoreAccessLibJNI.BoolInvokeResult_getBoolResult(swigCPtr, this);
  }

}
