/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public final class CommuExceptionType {
  public final static CommuExceptionType NO_EXCEPTION = new CommuExceptionType("NO_EXCEPTION", 0);
  public final static CommuExceptionType SOCKET_CONNECTION_FAIL = new CommuExceptionType("SOCKET_CONNECTION_FAIL");
  public final static CommuExceptionType WAIT_RESPONSE_TIMEOUT = new CommuExceptionType("WAIT_RESPONSE_TIMEOUT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CommuExceptionType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CommuExceptionType.class + " with value " + swigValue);
  }

  private CommuExceptionType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CommuExceptionType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CommuExceptionType(String swigName, CommuExceptionType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CommuExceptionType[] swigValues = { NO_EXCEPTION, SOCKET_CONNECTION_FAIL, WAIT_RESPONSE_TIMEOUT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

