/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public class DataValueItemVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DataValueItemVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataValueItemVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UtpCoreAccessLibJNI.delete_DataValueItemVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DataValueItemVector() {
    this(UtpCoreAccessLibJNI.new_DataValueItemVector__SWIG_0(), true);
  }

  public DataValueItemVector(long n) {
    this(UtpCoreAccessLibJNI.new_DataValueItemVector__SWIG_1(n), true);
  }

  public long size() {
    return UtpCoreAccessLibJNI.DataValueItemVector_size(swigCPtr, this);
  }

  public long capacity() {
    return UtpCoreAccessLibJNI.DataValueItemVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    UtpCoreAccessLibJNI.DataValueItemVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return UtpCoreAccessLibJNI.DataValueItemVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    UtpCoreAccessLibJNI.DataValueItemVector_clear(swigCPtr, this);
  }

  public void add(DataValueItem x) {
    UtpCoreAccessLibJNI.DataValueItemVector_add(swigCPtr, this, DataValueItem.getCPtr(x), x);
  }

  public DataValueItem get(int i) {
    long cPtr = UtpCoreAccessLibJNI.DataValueItemVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new DataValueItem(cPtr, false);
  }

  public void set(int i, DataValueItem val) {
    UtpCoreAccessLibJNI.DataValueItemVector_set(swigCPtr, this, i, DataValueItem.getCPtr(val), val);
  }

}
