/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public class EngineConfiguration {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EngineConfiguration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EngineConfiguration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UtpCoreAccessLibJNI.delete_EngineConfiguration(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EngineConfiguration() {
    this(UtpCoreAccessLibJNI.new_EngineConfiguration(), true);
  }

  public void addEngineConfigItem(String configItemName, String configItemValue) {
    UtpCoreAccessLibJNI.EngineConfiguration_addEngineConfigItem(swigCPtr, this, configItemName, configItemValue);
  }

  public void addAgent(String agentType, String agentName) {
    UtpCoreAccessLibJNI.EngineConfiguration_addAgent(swigCPtr, this, agentType, agentName);
  }

  public void addAgentNotifyScript(String agentName, String notifyId, String scriptId) {
    UtpCoreAccessLibJNI.EngineConfiguration_addAgentNotifyScript(swigCPtr, this, agentName, notifyId, scriptId);
  }

  public void addAgentConfigItem(String agentName, String configItemName, String configItemValue) {
    UtpCoreAccessLibJNI.EngineConfiguration_addAgentConfigItem(swigCPtr, this, agentName, configItemName, configItemValue);
  }

  public void addScript(String id, String[] content) {
    UtpCoreAccessLibJNI.EngineConfiguration_addScript(swigCPtr, this, id, content);
  }

  public void addStructuredScript(String id, ScriptContent content) {
    UtpCoreAccessLibJNI.EngineConfiguration_addStructuredScript(swigCPtr, this, id, ScriptContent.getCPtr(content), content);
  }

  public void addProgNotiType(ExecProgTypeEnum progNotiType) {
    UtpCoreAccessLibJNI.EngineConfiguration_addProgNotiType(swigCPtr, this, progNotiType.swigValue());
  }

  public void addGlobalMacro(String name, String value) {
    UtpCoreAccessLibJNI.EngineConfiguration_addGlobalMacro(swigCPtr, this, name, value);
  }

}
