/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public final class ExecStatus {
  public final static ExecStatus EXECUTE_STATUS_INVALID = new ExecStatus("EXECUTE_STATUS_INVALID", 0);
  public final static ExecStatus EXECUTE_STATUS_INIT = new ExecStatus("EXECUTE_STATUS_INIT");
  public final static ExecStatus EXECUTE_STATUS_READY = new ExecStatus("EXECUTE_STATUS_READY");
  public final static ExecStatus EXECUTE_STATUS_EXECUTING = new ExecStatus("EXECUTE_STATUS_EXECUTING");
  public final static ExecStatus EXECUTE_STATUS_PAUSING = new ExecStatus("EXECUTE_STATUS_PAUSING");
  public final static ExecStatus EXECUTE_STATUS_PAUSED = new ExecStatus("EXECUTE_STATUS_PAUSED");
  public final static ExecStatus EXECUTE_STATUS_STOPPING = new ExecStatus("EXECUTE_STATUS_STOPPING");
  public final static ExecStatus EXECUTE_STATUS_STOPPED = new ExecStatus("EXECUTE_STATUS_STOPPED");
  public final static ExecStatus EXECUTE_STATUS_COMPLETED = new ExecStatus("EXECUTE_STATUS_COMPLETED");
  public final static ExecStatus EXECUTE_STATUS_EXCEPTION_HANDLING = new ExecStatus("EXECUTE_STATUS_EXCEPTION_HANDLING");
  public final static ExecStatus EXECUTE_STATUS_WAITING_NETWORK = new ExecStatus("EXECUTE_STATUS_WAITING_NETWORK");
  public final static ExecStatus EXECUTE_STATUS_TERMINATED = new ExecStatus("EXECUTE_STATUS_TERMINATED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ExecStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ExecStatus.class + " with value " + swigValue);
  }

  private ExecStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ExecStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ExecStatus(String swigName, ExecStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ExecStatus[] swigValues = { EXECUTE_STATUS_INVALID, EXECUTE_STATUS_INIT, EXECUTE_STATUS_READY, EXECUTE_STATUS_EXECUTING, EXECUTE_STATUS_PAUSING, EXECUTE_STATUS_PAUSED, EXECUTE_STATUS_STOPPING, EXECUTE_STATUS_STOPPED, EXECUTE_STATUS_COMPLETED, EXECUTE_STATUS_EXCEPTION_HANDLING, EXECUTE_STATUS_WAITING_NETWORK, EXECUTE_STATUS_TERMINATED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

