/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public final class ExecProgTypeEnum {
  public final static ExecProgTypeEnum PROGTYPTE_INVALID = new ExecProgTypeEnum("PROGTYPTE_INVALID", 0);
  public final static ExecProgTypeEnum EXECUTION_BEGIN = new ExecProgTypeEnum("EXECUTION_BEGIN", 1);
  public final static ExecProgTypeEnum EXECUTION_END = new ExecProgTypeEnum("EXECUTION_END", 2);
  public final static ExecProgTypeEnum TESTCASE_BEGIN = new ExecProgTypeEnum("TESTCASE_BEGIN", 3);
  public final static ExecProgTypeEnum TESTCASE_END = new ExecProgTypeEnum("TESTCASE_END", 4);
  public final static ExecProgTypeEnum CHECKPOINT_BEGIN = new ExecProgTypeEnum("CHECKPOINT_BEGIN", 5);
  public final static ExecProgTypeEnum CHECKPOINT_END = new ExecProgTypeEnum("CHECKPOINT_END", 6);
  public final static ExecProgTypeEnum COMMAND_BEGIN = new ExecProgTypeEnum("COMMAND_BEGIN", 7);
  public final static ExecProgTypeEnum COMMAND_RESULT = new ExecProgTypeEnum("COMMAND_RESULT", 8);
  public final static ExecProgTypeEnum EXCEPTION_BEGIN = new ExecProgTypeEnum("EXCEPTION_BEGIN", 9);
  public final static ExecProgTypeEnum EXCEPTION_END = new ExecProgTypeEnum("EXCEPTION_END", 10);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ExecProgTypeEnum swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ExecProgTypeEnum.class + " with value " + swigValue);
  }

  private ExecProgTypeEnum(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ExecProgTypeEnum(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ExecProgTypeEnum(String swigName, ExecProgTypeEnum swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ExecProgTypeEnum[] swigValues = { PROGTYPTE_INVALID, EXECUTION_BEGIN, EXECUTION_END, TESTCASE_BEGIN, TESTCASE_END, CHECKPOINT_BEGIN, CHECKPOINT_END, COMMAND_BEGIN, COMMAND_RESULT, EXCEPTION_BEGIN, EXCEPTION_END };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

