/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public class ExecuteInvokeResult extends BoolInvokeResult {
  private long swigCPtr;

  protected ExecuteInvokeResult(long cPtr, boolean cMemoryOwn) {
    super(UtpCoreAccessLibJNI.ExecuteInvokeResult_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExecuteInvokeResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UtpCoreAccessLibJNI.delete_ExecuteInvokeResult(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ExecuteInvokeResult() {
    this(UtpCoreAccessLibJNI.new_ExecuteInvokeResult(), true);
  }

  public long getFailAgentCount() {
    return UtpCoreAccessLibJNI.ExecuteInvokeResult_getFailAgentCount(swigCPtr, this);
  }

  public boolean getAgentFailReason(long index, AgentFailReason agentReason) {
    return UtpCoreAccessLibJNI.ExecuteInvokeResult_getAgentFailReason(swigCPtr, this, index, AgentFailReason.getCPtr(agentReason), agentReason);
  }

}
