/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public class ExecProgItem {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ExecProgItem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExecProgItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UtpCoreAccessLibJNI.delete_ExecProgItem(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNotifType(ExecProgTypeEnum value) {
    UtpCoreAccessLibJNI.ExecProgItem_notifType_set(swigCPtr, this, value.swigValue());
  }

  public ExecProgTypeEnum getNotifType() {
    return ExecProgTypeEnum.swigToEnum(UtpCoreAccessLibJNI.ExecProgItem_notifType_get(swigCPtr, this));
  }

  public void setNotifContent(String[] value) {
    UtpCoreAccessLibJNI.ExecProgItem_notifContent_set(swigCPtr, this, value);
  }

  public String[] getNotifContent() {
    return UtpCoreAccessLibJNI.ExecProgItem_notifContent_get(swigCPtr, this);
  }

  public ExecProgItem() {
    this(UtpCoreAccessLibJNI.new_ExecProgItem(), true);
  }

}
