/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public class IAsyncCallResponseListener {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IAsyncCallResponseListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IAsyncCallResponseListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UtpCoreAccessLibJNI.delete_IAsyncCallResponseListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    UtpCoreAccessLibJNI.IAsyncCallResponseListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    UtpCoreAccessLibJNI.IAsyncCallResponseListener_change_ownership(this, swigCPtr, true);
  }

  public void initEngineResponse(BoolInvokeResult result, long engineSessionId) {
    UtpCoreAccessLibJNI.IAsyncCallResponseListener_initEngineResponse(swigCPtr, this, BoolInvokeResult.getCPtr(result), result, engineSessionId);
  }

  public void configEngineResponse(BoolInvokeResult result, long engineSessionId) {
    UtpCoreAccessLibJNI.IAsyncCallResponseListener_configEngineResponse(swigCPtr, this, BoolInvokeResult.getCPtr(result), result, engineSessionId);
  }

  public void analyzeScriptResponse(AnalyzeInvokeResult result, long engineSessionId) {
    UtpCoreAccessLibJNI.IAsyncCallResponseListener_analyzeScriptResponse(swigCPtr, this, AnalyzeInvokeResult.getCPtr(result), result, engineSessionId);
  }

  public void getAvailableAgentsResponse(ScriptAgentVector scriptAgents, AgentLiveListVector liveAgents, long engineSessionId) {
    UtpCoreAccessLibJNI.IAsyncCallResponseListener_getAvailableAgentsResponse(swigCPtr, this, ScriptAgentVector.getCPtr(scriptAgents), scriptAgents, AgentLiveListVector.getCPtr(liveAgents), liveAgents, engineSessionId);
  }

  public void startExecutionResponse(ExecuteInvokeResult result, long engineSessionId) {
    UtpCoreAccessLibJNI.IAsyncCallResponseListener_startExecutionResponse(swigCPtr, this, ExecuteInvokeResult.getCPtr(result), result, engineSessionId);
  }

  public IAsyncCallResponseListener() {
    this(UtpCoreAccessLibJNI.new_IAsyncCallResponseListener(), true);
    UtpCoreAccessLibJNI.IAsyncCallResponseListener_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
