/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public class ICommuExceptionListener {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ICommuExceptionListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ICommuExceptionListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UtpCoreAccessLibJNI.delete_ICommuExceptionListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    UtpCoreAccessLibJNI.ICommuExceptionListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    UtpCoreAccessLibJNI.ICommuExceptionListener_change_ownership(this, swigCPtr, true);
  }

  public void commuExceptionNotify(CommuExceptionType exception, long engineSessionId) {
    UtpCoreAccessLibJNI.ICommuExceptionListener_commuExceptionNotify(swigCPtr, this, exception.swigValue(), engineSessionId);
  }

  public ICommuExceptionListener() {
    this(UtpCoreAccessLibJNI.new_ICommuExceptionListener(), true);
    UtpCoreAccessLibJNI.ICommuExceptionListener_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
