/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public class IExecProgListener {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IExecProgListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IExecProgListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UtpCoreAccessLibJNI.delete_IExecProgListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    UtpCoreAccessLibJNI.IExecProgListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    UtpCoreAccessLibJNI.IExecProgListener_change_ownership(this, swigCPtr, true);
  }

  public void update(ExecProgItem progNotify, long engineSessionId) {
    UtpCoreAccessLibJNI.IExecProgListener_update(swigCPtr, this, ExecProgItem.getCPtr(progNotify), progNotify, engineSessionId);
  }

  public IExecProgListener() {
    this(UtpCoreAccessLibJNI.new_IExecProgListener(), true);
    UtpCoreAccessLibJNI.IExecProgListener_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
