/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public class IMonitorDataListener {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IMonitorDataListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IMonitorDataListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UtpCoreAccessLibJNI.delete_IMonitorDataListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    UtpCoreAccessLibJNI.IMonitorDataListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    UtpCoreAccessLibJNI.IMonitorDataListener_change_ownership(this, swigCPtr, true);
  }

  public void dataChanged(MonitoredData data, long engineSessionId, String timestamp) {
    UtpCoreAccessLibJNI.IMonitorDataListener_dataChanged(swigCPtr, this, MonitoredData.getCPtr(data), data, engineSessionId, timestamp);
  }

  public IMonitorDataListener() {
    this(UtpCoreAccessLibJNI.new_IMonitorDataListener(), true);
    UtpCoreAccessLibJNI.IMonitorDataListener_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
