/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public class LiveAgentVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected LiveAgentVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LiveAgentVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UtpCoreAccessLibJNI.delete_LiveAgentVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LiveAgentVector() {
    this(UtpCoreAccessLibJNI.new_LiveAgentVector__SWIG_0(), true);
  }

  public LiveAgentVector(long n) {
    this(UtpCoreAccessLibJNI.new_LiveAgentVector__SWIG_1(n), true);
  }

  public long size() {
    return UtpCoreAccessLibJNI.LiveAgentVector_size(swigCPtr, this);
  }

  public long capacity() {
    return UtpCoreAccessLibJNI.LiveAgentVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    UtpCoreAccessLibJNI.LiveAgentVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return UtpCoreAccessLibJNI.LiveAgentVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    UtpCoreAccessLibJNI.LiveAgentVector_clear(swigCPtr, this);
  }

  public void add(LiveAgent x) {
    UtpCoreAccessLibJNI.LiveAgentVector_add(swigCPtr, this, LiveAgent.getCPtr(x), x);
  }

  public LiveAgent get(int i) {
    long cPtr = UtpCoreAccessLibJNI.LiveAgentVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new LiveAgent(cPtr, false);
  }

  public void set(int i, LiveAgent val) {
    UtpCoreAccessLibJNI.LiveAgentVector_set(swigCPtr, this, i, LiveAgent.getCPtr(val), val);
  }

}
