/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public class LiveAgent {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected LiveAgent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LiveAgent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UtpCoreAccessLibJNI.delete_LiveAgent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getAgentId() {
    return UtpCoreAccessLibJNI.LiveAgent_getAgentId(swigCPtr, this);
  }

  public String getAgentType() {
    return UtpCoreAccessLibJNI.LiveAgent_getAgentType(swigCPtr, this);
  }

  public String getAgentName() {
    return UtpCoreAccessLibJNI.LiveAgent_getAgentName(swigCPtr, this);
  }

  public String getAgentDesc() {
    return UtpCoreAccessLibJNI.LiveAgent_getAgentDesc(swigCPtr, this);
  }

  public LiveAgent() {
    this(UtpCoreAccessLibJNI.new_LiveAgent(), true);
  }

}
