/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public final class MonitorDataTypeEnum {
  public final static MonitorDataTypeEnum DATATYPTE_INVALID = new MonitorDataTypeEnum("DATATYPTE_INVALID", 0);
  public final static MonitorDataTypeEnum DATATYPTE_STRING = new MonitorDataTypeEnum("DATATYPTE_STRING");
  public final static MonitorDataTypeEnum DATATYPTE_ARRAY = new MonitorDataTypeEnum("DATATYPTE_ARRAY");
  public final static MonitorDataTypeEnum DATATYPTE_BINARY = new MonitorDataTypeEnum("DATATYPTE_BINARY");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MonitorDataTypeEnum swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MonitorDataTypeEnum.class + " with value " + swigValue);
  }

  private MonitorDataTypeEnum(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MonitorDataTypeEnum(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private MonitorDataTypeEnum(String swigName, MonitorDataTypeEnum swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static MonitorDataTypeEnum[] swigValues = { DATATYPTE_INVALID, DATATYPTE_STRING, DATATYPTE_ARRAY, DATATYPTE_BINARY };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

