/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public class MonitoredData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MonitoredData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MonitoredData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UtpCoreAccessLibJNI.delete_MonitoredData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getDataName() {
    return UtpCoreAccessLibJNI.MonitoredData_getDataName(swigCPtr, this);
  }

  public MonitorDataTypeEnum getDataType() {
    return MonitorDataTypeEnum.swigToEnum(UtpCoreAccessLibJNI.MonitoredData_getDataType(swigCPtr, this));
  }

  public DataValueItemVector getDataValue() {
    return new DataValueItemVector(UtpCoreAccessLibJNI.MonitoredData_getDataValue(swigCPtr, this), false);
  }

  public MonitoredData() {
    this(UtpCoreAccessLibJNI.new_MonitoredData(), true);
  }

}
