/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public class ScriptAgentVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ScriptAgentVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ScriptAgentVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UtpCoreAccessLibJNI.delete_ScriptAgentVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ScriptAgentVector() {
    this(UtpCoreAccessLibJNI.new_ScriptAgentVector(), true);
  }

  public void add(ScriptAgent agent) {
    UtpCoreAccessLibJNI.ScriptAgentVector_add(swigCPtr, this, ScriptAgent.getCPtr(agent), agent);
  }

  public int size() {
    return UtpCoreAccessLibJNI.ScriptAgentVector_size(swigCPtr, this);
  }

  public ScriptAgent get(int i) {
    long cPtr = UtpCoreAccessLibJNI.ScriptAgentVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new ScriptAgent(cPtr, false);
  }

}
