/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public class ScriptCmd {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ScriptCmd(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ScriptCmd obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UtpCoreAccessLibJNI.delete_ScriptCmd(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ScriptCmd() {
    this(UtpCoreAccessLibJNI.new_ScriptCmd(), true);
  }

  public void addCmdField(String cmdfield) {
    UtpCoreAccessLibJNI.ScriptCmd_addCmdField(swigCPtr, this, cmdfield);
  }

}
