/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public class ScriptAgent {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ScriptAgent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ScriptAgent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UtpCoreAccessLibJNI.delete_ScriptAgent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getAgentName() {
    return UtpCoreAccessLibJNI.ScriptAgent_getAgentName(swigCPtr, this);
  }

  public String getAgentType() {
    return UtpCoreAccessLibJNI.ScriptAgent_getAgentType(swigCPtr, this);
  }

  public ScriptAgent() {
    this(UtpCoreAccessLibJNI.new_ScriptAgent(), true);
  }

}
