/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public class ScriptContent {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ScriptContent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ScriptContent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UtpCoreAccessLibJNI.delete_ScriptContent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ScriptContent() {
    this(UtpCoreAccessLibJNI.new_ScriptContent(), true);
  }

  public void addScriptCmd(ScriptCmd cmd) {
    UtpCoreAccessLibJNI.ScriptContent_addScriptCmd(swigCPtr, this, ScriptCmd.getCPtr(cmd), cmd);
  }

}
