/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public class SelectedAgent {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SelectedAgent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SelectedAgent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UtpCoreAccessLibJNI.delete_SelectedAgent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getScriptAgentName() {
    return UtpCoreAccessLibJNI.SelectedAgent_getScriptAgentName(swigCPtr, this);
  }

  public String getAgentId() {
    return UtpCoreAccessLibJNI.SelectedAgent_getAgentId(swigCPtr, this);
  }

  public void setScriptAgentName(String name) {
    UtpCoreAccessLibJNI.SelectedAgent_setScriptAgentName(swigCPtr, this, name);
  }

  public void setAgentId(String id) {
    UtpCoreAccessLibJNI.SelectedAgent_setAgentId(swigCPtr, this, id);
  }

  public SelectedAgent() {
    this(UtpCoreAccessLibJNI.new_SelectedAgent(), true);
  }

}
