/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public class SelectedAgentVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SelectedAgentVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SelectedAgentVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UtpCoreAccessLibJNI.delete_SelectedAgentVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SelectedAgentVector() {
    this(UtpCoreAccessLibJNI.new_SelectedAgentVector__SWIG_0(), true);
  }

  public SelectedAgentVector(long n) {
    this(UtpCoreAccessLibJNI.new_SelectedAgentVector__SWIG_1(n), true);
  }

  public long size() {
    return UtpCoreAccessLibJNI.SelectedAgentVector_size(swigCPtr, this);
  }

  public long capacity() {
    return UtpCoreAccessLibJNI.SelectedAgentVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    UtpCoreAccessLibJNI.SelectedAgentVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return UtpCoreAccessLibJNI.SelectedAgentVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    UtpCoreAccessLibJNI.SelectedAgentVector_clear(swigCPtr, this);
  }

  public void add(SelectedAgent x) {
    UtpCoreAccessLibJNI.SelectedAgentVector_add(swigCPtr, this, SelectedAgent.getCPtr(x), x);
  }

  public SelectedAgent get(int i) {
    long cPtr = UtpCoreAccessLibJNI.SelectedAgentVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new SelectedAgent(cPtr, false);
  }

  public void set(int i, SelectedAgent val) {
    UtpCoreAccessLibJNI.SelectedAgentVector_set(swigCPtr, this, i, SelectedAgent.getCPtr(val), val);
  }

}
