/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public class UtpCoreAccessLib {
  public static void initUtpCoreAccess() {
    UtpCoreAccessLibJNI.initUtpCoreAccess();
  }

  public static void releaseUtpCoreAccess() {
    UtpCoreAccessLibJNI.releaseUtpCoreAccess();
  }

}
