/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.UtpCoreAccessLib;

public class UtpEngine {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UtpEngine(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UtpEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UtpCoreAccessLibJNI.delete_UtpEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UtpEngine() {
    this(UtpCoreAccessLibJNI.new_UtpEngine(), true);
  }

  public boolean initEngineAsClient(long domainId, String usrAccount) {
    return UtpCoreAccessLibJNI.UtpEngine_initEngineAsClient(swigCPtr, this, domainId, usrAccount);
  }

  public boolean initEngineReq(String utpCoreAddr, long utpCorePort) {
    return UtpCoreAccessLibJNI.UtpEngine_initEngineReq(swigCPtr, this, utpCoreAddr, utpCorePort);
  }

  public boolean configEngineReq(EngineConfiguration config) {
    return UtpCoreAccessLibJNI.UtpEngine_configEngineReq(swigCPtr, this, EngineConfiguration.getCPtr(config), config);
  }

  public boolean analyzeScriptReq(String scriptId) {
    return UtpCoreAccessLibJNI.UtpEngine_analyzeScriptReq(swigCPtr, this, scriptId);
  }

  public boolean getAvailableAgentsReq(String domainName) {
    return UtpCoreAccessLibJNI.UtpEngine_getAvailableAgentsReq(swigCPtr, this, domainName);
  }

  public boolean startExecutionReq(SelectedAgentVector selectedAgents) {
    return UtpCoreAccessLibJNI.UtpEngine_startExecutionReq(swigCPtr, this, SelectedAgentVector.getCPtr(selectedAgents), selectedAgents);
  }

  public boolean stopExecution() {
    return UtpCoreAccessLibJNI.UtpEngine_stopExecution(swigCPtr, this);
  }

  public boolean pauseExecution() {
    return UtpCoreAccessLibJNI.UtpEngine_pauseExecution(swigCPtr, this);
  }

  public boolean resumeExecution() {
    return UtpCoreAccessLibJNI.UtpEngine_resumeExecution(swigCPtr, this);
  }

  public boolean singleStepExecution() {
    return UtpCoreAccessLibJNI.UtpEngine_singleStepExecution(swigCPtr, this);
  }

  public void setAsyncCallResponseListener(IAsyncCallResponseListener listener) {
    UtpCoreAccessLibJNI.UtpEngine_setAsyncCallResponseListener(swigCPtr, this, IAsyncCallResponseListener.getCPtr(listener), listener);
  }

  public void setMonitorDataListener(IMonitorDataListener listener) {
    UtpCoreAccessLibJNI.UtpEngine_setMonitorDataListener(swigCPtr, this, IMonitorDataListener.getCPtr(listener), listener);
  }

  public void setExecProgListener(IExecProgListener listener) {
    UtpCoreAccessLibJNI.UtpEngine_setExecProgListener(swigCPtr, this, IExecProgListener.getCPtr(listener), listener);
  }

  public void setExecStatusListener(IExecStatusListener listener) {
    UtpCoreAccessLibJNI.UtpEngine_setExecStatusListener(swigCPtr, this, IExecStatusListener.getCPtr(listener), listener);
  }

  public void setCommuExceptionListener(ICommuExceptionListener listener) {
    UtpCoreAccessLibJNI.UtpEngine_setCommuExceptionListener(swigCPtr, this, ICommuExceptionListener.getCPtr(listener), listener);
  }

  public long getEngineSessionId() {
    return UtpCoreAccessLibJNI.UtpEngine_getEngineSessionId(swigCPtr, this);
  }

  public boolean releaseEngine() {
    return UtpCoreAccessLibJNI.UtpEngine_releaseEngine(swigCPtr, this);
  }

}
