/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.convertorMgr;

public class ConvertorMgrLibJNI {
  public final static native void initConvertorMgr();
  public final static native long new_ExtNameVector();
  public final static native void delete_ExtNameVector(long jarg1);
  public final static native long ExtNameVector_size(long jarg1, ExtNameVector jarg1_);
  public final static native String ExtNameVector_get(long jarg1, ExtNameVector jarg1_, int jarg2);
  public final static native String ConvertResultItem_getResultItemName(long jarg1, ConvertResultItem jarg1_);
  public final static native String ConvertResultItem_getResultItemContent(long jarg1, ConvertResultItem jarg1_);
  public final static native long new_ConvertResultItem();
  public final static native void delete_ConvertResultItem(long jarg1);
  public final static native long new_ConvertResultItemVector();
  public final static native void delete_ConvertResultItemVector(long jarg1);
  public final static native long ConvertResultItemVector_size(long jarg1, ConvertResultItemVector jarg1_);
  public final static native long ConvertResultItemVector_get(long jarg1, ConvertResultItemVector jarg1_, int jarg2);
  public final static native void ConvertorMgr_getAllSupportExtNames(long jarg1, ConvertorMgr jarg1_, int jarg2, long jarg3, ExtNameVector jarg3_);
  public final static native boolean ConvertorMgr_convert(long jarg1, ConvertorMgr jarg1_, int jarg2, String jarg3, String jarg4, String jarg5, long jarg6, ConvertResultItemVector jarg6_);
  public final static native long new_ConvertorMgr();
  public final static native void delete_ConvertorMgr(long jarg1);
}
