/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.convertorMgr;

public class ConvertorMgr {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ConvertorMgr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConvertorMgr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ConvertorMgrLibJNI.delete_ConvertorMgr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void initConvertorMgr() {
    ConvertorMgrLibJNI.ConvertorMgr_initConvertorMgr();
  }

  public static void getAllSupportExtNames(ConvertorType type, ExtNameVector extNameArray) {
    ConvertorMgrLibJNI.ConvertorMgr_getAllSupportExtNames(type.swigValue(), ExtNameVector.getCPtr(extNameArray), extNameArray);
  }

  public static boolean convert(ConvertorType type, String extName, String toConvertFileName, String toConvertContent, ConvertResultItemVector convRsltItemArray) {
    return ConvertorMgrLibJNI.ConvertorMgr_convert(type.swigValue(), extName, toConvertFileName, toConvertContent, ConvertResultItemVector.getCPtr(convRsltItemArray), convRsltItemArray);
  }

  public ConvertorMgr() {
    this(ConvertorMgrLibJNI.new_ConvertorMgr(), true);
  }

}
