/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.convertorMgr;

public class ConvertResultItem {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ConvertResultItem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConvertResultItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ConvertorMgrLibJNI.delete_ConvertResultItem(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getResultItemName() {
    return ConvertorMgrLibJNI.ConvertResultItem_getResultItemName(swigCPtr, this);
  }

  public String getResultItemContent() {
    return ConvertorMgrLibJNI.ConvertResultItem_getResultItemContent(swigCPtr, this);
  }

  public ConvertResultItem() {
    this(ConvertorMgrLibJNI.new_ConvertResultItem(), true);
  }

}
