/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.convertorMgr;

public class ConvertResultItemVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ConvertResultItemVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConvertResultItemVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.macrosoftsys.utpDbcConvertLib.ConvertorMgrLibJNI.delete_ConvertResultItemVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ConvertResultItemVector() {
    this(com.macrosoftsys.utpDbcConvertLib.ConvertorMgrLibJNI.new_ConvertResultItemVector(), true);
  }

  public long size() {
    return com.macrosoftsys.utpDbcConvertLib.ConvertorMgrLibJNI.ConvertResultItemVector_size(swigCPtr, this);
  }

  public ConvertResultItem get(int i) {
    long cPtr = com.macrosoftsys.utpDbcConvertLib.ConvertorMgrLibJNI.ConvertResultItemVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new ConvertResultItem(cPtr, false);
  }

}
