/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.convertorMgr;

public final class ConvertorType {
  public final static ConvertorType PROTOCOL_CONVERTOR = new ConvertorType("PROTOCOL_CONVERTOR", 0);
  public final static ConvertorType SIGNAL_CONVERTOR = new ConvertorType("SIGNAL_CONVERTOR", 1);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ConvertorType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ConvertorType.class + " with value " + swigValue);
  }

  private ConvertorType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ConvertorType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ConvertorType(String swigName, ConvertorType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ConvertorType[] swigValues = { PROTOCOL_CONVERTOR, SIGNAL_CONVERTOR };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

