/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.macrosoftsys.convertorMgr;

public class ExtNameVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ExtNameVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExtNameVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ConvertorMgrLibJNI.delete_ExtNameVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ExtNameVector() {
    this(ConvertorMgrLibJNI.new_ExtNameVector(), true);
  }

  public long size() {
    return ConvertorMgrLibJNI.ExtNameVector_size(swigCPtr, this);
  }

  public String get(int i) {
    return ConvertorMgrLibJNI.ExtNameVector_get(swigCPtr, this, i);
  }

}
